const gen89Abilities: { [key: string]: string } = {
    "ball-fetch": "If the Pokémon is not holding an item, it will fetch the Poké Ball from the first failed throw of the battle.",
    "cotton-down": "When the Pokémon is hit by an attack, it scatters cotton fluff around and lowers the Speed stat of all Pokémon except itself.",
    "curious-medicine": "When the Pokémon is brought into battle, any stat alterations of allies are removed.",
    "dauntless-shield": "Boosts the Pokémon's Defense stat when the Pokémon enters a battle.",
    "dragons-maw": "Increases the damage inflicted by Dragon-type moves by 50%.",
    "gorilla-tactics": "Boosts the Pokémon's Attack stat but only allows the use of the first selected move.",
    "gulp-missile": "When the Pokémon uses Surf or Dive, it will come back with prey. When it takes damage, it will spit out the prey to attack.",
    "hunger-switch": "The Pokémon changes its form, alternating between its Full Belly Mode and Hangry Mode after the end of each turn.",
    "ice-face": "The Pokémon's ice head can take a physical attack as a substitute, but the attack also changes the Pokémon's appearance. The ice will be restored when it hails.",
    "ice-scales": "The Pokémon is protected by ice scales, which halve the damage taken from special moves.",
    "intrepid-sword": "Boosts the Pokémon's Attack stat when the Pokémon enters a battle.",
    "libero": "Changes the Pokémon's type to the type of the move it's about to use.",
    "mimicry": "Changes the Pokémon's type depending on the terrain.",
    "mirror-armor": "Bounces back only the stat-lowering effects that the Pokémon receives.",
    "neutralizing-gas": "If the Pokémon with Neutralizing Gas is in the battle, the effects of all Pokémon's Abilities will be nullified or will not be triggered.",
    "pastel-veil": "Protects the Pokémon and its ally Pokémon from being poisoned.",
    "perish-body": "When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.",
    "power-spot": "Just being next to the Pokémon powers up moves.",
    "propeller-tail": "Ignores the effects of opposing Pokémon's Abilities and moves that draw in moves.",
    "punk-rock": "Boosts the power of sound-based moves. The Pokémon also takes half the damage from these kinds of moves.",
    "quick-draw": "At the start of each turn, this Pokémon has a 30% chance of moving first in the Speed Priority Bracket.",
    "ripen": "Ripens Berries and doubles their effect.",
    "sand-spit": "The Pokémon creates a sandstorm when it's hit by an attack.",
    "screen-cleaner": "When the Pokémon enters a battle, the effects of Light Screen, Reflect, and Aurora Veil are nullified for both opposing and ally Pokémon.",
    "stalwart": "Ignores the effects of opposing Pokémon's Abilities and moves that draw in moves.",
    "steam-engine": "Boosts the Pokémon's Speed stat drastically if hit by a Fire- or Water-type move.",
    "steely-spirit": "Powers up ally Pokémon's Steel-type moves.",
    "transistor": "Increases the damage inflicted by Electric-type moves by 50%.",
    "unseen-fist": "The Pokémon can deal damage with moves that make physical contact, even if the target is protected.",
    "wandering-spirit": "The Pokémon exchanges Abilities with a Pokémon that hits it with a move that makes direct contact."
  };

  export { gen89Abilities }